### PR TITLE
Fix & improve `github.createTag`

### LINKED ISSUE #12: Check if tag exists without getting all tags
Since the [GitHub Java API](https://github.com/hub4j/github-api) doesn't have a `getTagByName` method, I iterated over `listTags` in #8 to implement `!createTag`.

Looking into things further, while the [REST API](https://docs.github.com/en/rest) has no endpoint for getting a specific tag, the [GraphQL API](https://docs.github.com/en/graphql) is capable of handling these kinda requests.

In fact, that is exactly how GitHub CLI's [`--verify-tag` option is implemented](https://github.com/cli/cli/blob/ec812a16f77df5f196189e9871722b9b601143bc/pkg/cmd/release/create/http.go#L30-L47).

We can use this query to determine if a tag exists, by checking whether `data.repository.ref.id` is `null`:

```graphql
query($owner:String!, $repo:String!, $tag:String!) {
  repository(owner: $owner, name: $repo) {
    ref(qualifiedName: $tag) {
      id
    }
  }
}
```

<details><summary>Valid request</summary>
<p>

#### Variables
```json
{
  "owner": "MinecraftFreecam",
  "repo": "Freecam",
  "tag": "refs/tags/v1.2.3"
}
```

#### Response
```json
{
  "data": {
    "repository": {
      "ref": {
        "id": "REF_kwDOGh1Gq7ByZWZzL3RhZ3MvdjEuMi4z"
      }
    }
  }
}
```

</p>
</details> 

<details><summary>Missing request</summary>
<p>

#### Variables
```json
{
  "owner": "MinecraftFreecam",
  "repo": "Freecam",
  "tag": "refs/tags/invalid-tag-name"
}
```

#### Response
```json
{
  "data": {
    "repository": {
      "ref": {
        "id": null
      }
    }
  }
}
```

</p>
</details> 

I believe the GitHub Java API has a way to run GraphQL queries, so this should be fairly simple. Maybe they'd be interested in having `GHRepository.containsTag(String name)` upstream :thinking:

### LINKED ISSUE #14: [BUG] `github.createTag` is inverted
- Setting `createTag = true` should allow creating a release when the tag does not yet exist.
- Setting `createTag = false` should fail when creating a release for a tag that doesn't exist.

Currently, the check is performed before creating a new release, and only if `createTag = false`. However the logic is inverted and creating will fail if the tag _does_ exist.

### Also

I'm wondering how this should interact with `github.draft`. Theoretically, it shouldn't matter whether the tag exists when creating a draft, because releases don't create a git tag until they get "published" (`draft=false`).

### PR DESCRIPTION
**Pull request by MattSturgeon**
Fixed the inverted logic and avoided the need to fetch all repo tags by using `getRef` instead.

I tested out the [`hasRef` implementation](https://github.com/firstdarkdev/modpublisher/pull/15/files#diff-1547efb0ef96fae2452eb434ab9306b94511b1065ccf92c9e6187c90bb870842R176-R195) as follows:

<details><summary>Details</summary>
<p>

```kotlin
// Some boilerplate setting up github, token & repo omitted
fun main() {
    sequenceOf("v1.2.3", "foo", "random", "v1.2.2", "v1.2.3+mc1.20.4")
        .forEach {
            println("Checking if ${repo.fullName} has tag named $it")
            val has = repo.hasTag(it)
            println("  It ${if (has) "does" else "does not"}!")
        }

}

fun GHRepository.hasTag(tag: String): Boolean {
    try {
        this.getRef("refs/tags/$tag")
        return true
    } catch (e: GHFileNotFoundException) {
        return false
    } catch (e: IOException) {
        throw IOException("Error checking remote tag", e)
    }
}
```

Which prints:

```
Checking if MinecraftFreecam/Freecam has tag named v1.2.3
  It does!
Checking if MinecraftFreecam/Freecam has tag named foo
  It does not!
Checking if MinecraftFreecam/Freecam has tag named random
  It does not!
Checking if MinecraftFreecam/Freecam has tag named v1.2.2
  It does!
Checking if MinecraftFreecam/Freecam has tag named v1.2.3+mc1.20.4
  It does!
```

</p>
</details> 

Fixes #12
Fixes #14

### CODE REVIEW

File: src/main/java/com/hypherionmc/modpublisher/tasks/GithubUploadTask.java [hunk 1]
```diff
@@ -109,15 +109,11 @@ public void upload() throws Exception {
...
-                // FIXME It'd be nice to get tag by name, but GHRepository doesn't expose an API to do that
-                // For now, just iterate thorough all tags on the repo...
-                for (GHTag ghTag : ghRepository.listTags()) {
-                    if (tag.equals(ghTag.getName())) {
-                        project.getLogger().warn("Create tag for GitHub Release is disabled and tag {} already exists", tag);
-                        return;
-                    }
-                }
+            // FIXME this check doesn't make sense when `github.draft` is true,
+            //       because draft releases don't create a tag anyway...
```
Comment (MattSturgeon) [inline src/main/java/com/hypherionmc/modpublisher/tasks/GithubUploadTask.java:113]: This API was broken and is marked "experimental". Should we take this opportunity to change behaviour for the _creating a draft_ scenario?

What do you think the best approach is?
- rename the option for clarity?
- just update the docs?
- add draft/public specific options?
- take a string/enum instead of a boolean?

**Comment by hypherionmc** [comment]
Hey. Just checking in. I've been so busy I forgot to check back on things.

Is this PR ready to be merged, or do you have more you want to do first?

**Comment by MattSturgeon** [comment]
> I've been so busy I forgot to check back on things.

No worries :+1: 

> Is this PR ready to be merged

Should be good to go, unless you request any changes.

> do you have more you want to do first?

It doesn't address [this comment](https://github.com/firstdarkdev/modpublisher/pull/15/files#r1552167519) or any of the ideas discussed in #16, but it does fix actual issues in the current implementation.

Those other changes are out of scope of this PR, I think.

**Review by hypherionmc — APPROVED** [review]
